#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\e[38;5;118m${cuseco} → \e[38;5;11mvio-helper:\e[38;5;118mcp"
	echo -e "\e[38;5;118m⇒  \e[38;5;195mcopia todos los argumentos en el dir de IMPRIMIR at home
	⭐ \e[38;5;9mt option \e[38;5;195mpara tree el IMPRIMIR at home \e[38;5;118m
	⭐ \e[38;5;9md option \e[38;5;195mpara copy recursively todo un directorio 
	⭐ \e[38;5;9mc option \e[38;5;195mpara clean → select file to rm; press enter to rm all
  	❤️️ 
\t\\e[38;5;43mFor example:
\t 👉 \e[38;5;228m${cuseco} -$o\e[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
##DIRECTORIES 
direimp="/home/violeta/IMPRIMIR"
##FILES
#VARIABLES
impdir=false
recursicopy=""

while getopts ":ehdtc" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		d)
			impdir=true
			;;
		t)
			tree ${direimp}  
			exit
			;;
		c)
			select filetoremove in $(find ${direimp} -type f && echo "exit") 
			do
				if [[ ${filetoremove} = "exit" ]]; then
					echo -e "remove all????"
					if asksure; then
						rm ${direimp}/*
					fi
					exit	
				fi	
				rm ${filetoremove} 
			    break
		    done
		    exit
			;;	   
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN

toimprimir="$@"

[[ ${impdir} = true ]] && recursicopy="-r"
cp ${recursicopy} ${toimprimir} ${direimp}    
tree ${direimp} 2>/dev/null
