#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
	echo -e "\e[38;5;118m${cuseco} ⇒  \e[38;5;11mtype:\e[38;5;118msalud ⇒  wdisplay"
	echo -e "\e[38;5;195m display \e[38;5;11m⭐ un butt ejercicio \e[38;5;11m⭐ \e[38;5;195m cada \e[38;5;212m crontime ❤️️ 
	\e[38;5;118m★ \e[38;5;9moption nopt \e[38;5;195mde momento 🚁  
	\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
	return 25
}

source Asksure.fu
source Opte.fu
source Continua.fu
source Echocolors.fu # black red green yellow blue magenta cyan white pink orange whiteguay @+N

while getopts ":eh" o; do
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis 2>/dev/null
			[[ "$?" == 25  ]] || echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))


exesdir="/home/violeta/PROYECTO/basicos/vya/bigbutt-exers"
bexes=( "firehydrant.png" "legbridge-dogvariant.png" "legbridge.png" "single-deadlift-onair.png" "single-deadlift.png" "weigthed-squats.png" )

/usr/games/xcowsay -t 0 "Butt time ⚡" 

whichone=$(($RANDOM % 5))
display ${exesdir}/${bexes[${whichone}]}  
