#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\e[38;5;118m${cuseco} → \e[38;5;11mvio-helpers:\e[38;5;118m sed vlcconfig"
	echo -e "\e[38;5;118m⇒  \e[38;5;195mcopiado básico de geus-editvlcspeed 
	⭐\e[38;5;195m puede mejorar!! ⭐ ❤️️  \e[38;5;228mde momoento, no opts 
\t\\e[38;5;43mFor example:
\t\\e[38;5;228m${cuseco} -$o\e[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
##DIRECTORIES 
##FILES
vlcconfig=/home/violeta/.config/vlc/vlcrc
#VARIABLES
onlysee=false

while getopts ":eho" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		o)
			onlysee=true
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN
grep -A 1 "VIO-PLAY-SPEED-hasiera" ${vlcconfig} | grep "rate=" 
[[ ${onlysee} = true ]] && exit 
read -p "enter speed → " vspeed
sed -i "/##VIO-PLAY-SPEED-hasiera/,/##VIO-PLAY-SPEED-bukaera/{d}" ${vlcconfig}
sed -i "/# Playback speed (float)/a\
	##VIO-PLAY-SPEED-hasiera\nrate=$vspeed\n##VIO-PLAY-SPEED-bukaera
" ${vlcconfig}
