#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mselect and vim → de find xargs grep ⇒  in DEBIAN USR LOCAL"
echo -e "	\\e[38;5;195m A;ade select a \\e[38;5;11m⭐\\e[38;5;195m gigul!\\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
#VARIABLES
dterm=$1
### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))

[[ ! $1 ]] && echo -e "\e[38;5;118mpero qué término???"  && exit


select f in $(gigul ${dterm} | vawk : 1)
do
	vim $f
	break
done 
