#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;195m\\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mbin work ⇒  mv → /bin/funciones"
echo -e " \e[38;5;195m sends cprue/sh files to BIN without .sh \\e[38;5;212m ❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m\\n
    "
}

#VARIABLES

##DIRECTORIES
ddir=/home/violeta/bin/funciones/fproespecific
##FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu
#gralgetops

### MAIN
while getopts ":eh" o; do 
	gralGetops
done
shift $((OPTIND-1))
# ♥

dshfile=$1
dfile=$(realpath ${dshfile}) 

echo -e "\e[38;5;195m Type \\e[38;5;118m[Aa] \\e[38;5;195m for a \\e[38;5;118mgeneral \\e[38;5;195m function. \\e[38;5;9m[Ee] \\e[38;5;195m for \\e[38;5;9mproespecific"        
if asksure; then
	ddir=${ddir%fproespecific}  
fi

mv ${dfile} ${ddir}   
tree /home/violeta/bin/funciones
