#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mgeus → vim ⇒  select, array con mapfile, SECONDS var, log function"
echo -e "	\\e[38;5;195m Select an audio from geus playsists.., and [38;5;118mdo[38;5;11m ⭐[38;5;118mit!!!  \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m
    "
}

## SOURCES
# FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu # snippet → sops
source Logtime.fu 

gvallwaysfile=/home/violeta/bin/geush/auxiliares/vallways/geus-vallways.aux
source ${gvallwaysfile} 
source ${funcsdir}/echonthego.fu
source ${funcsdir}/editvlcrc.fu
source ${funcsdir}/erabaki_hizkuntza.fu

gvonthegofile=/home/violeta/bin/geush/auxiliares/vonthego/geus-vonthego.aux
source ${gvonthegofile}  

erabaki_hizkuntza
getvlcspeed


##DIRECTORIES
##FILES
tlogfile=${transdir}/.transcripciones.log
tralogfile="${transdir}/${clipname%.mp3}.transcript"
#refdatefile...
#VARIABLES
myspeed=false

### MAIN
while getopts ":ehs" o; do 
	    case "${o}" in
        e)
            opte
            exit
            ;;
        h)
            #whatis
            echo -e "PENDING whatis!! 🔥 "
            exit
            ;;
        s)
            editvlcspeed 
            ;;
        \?)
            echo "invalid option: -$OPTARG"
            exit
            ;;
    esac
done
shift $((OPTIND-1))

#si no hay option s, aplicar la funct editspeed con $1==1
#[[ ${myspeed} = false ]] && editspeed 1

mapfile -t playlists < <( find ${playldir}/pl-listen* -exec basename {} \; | sort -r ) # -type f -newer ${refdatefile}... 

echo -e "\e[38;5;212m❤️️ ❤️️ ❤️️ ❤️️ \\e[38;5;11m❤️️ \\e[38;5;212m Happy \\e[38;5;195m L\\e[38;5;11m ⭐ \\e[38;5;195m I\\e[38;5;11m ⭐ \\e[38;5;195m S\\e[38;5;11m ⭐ \\e[38;5;195m T\\e[38;5;11m ⭐ \\e[38;5;195m E\\e[38;5;11m ⭐ \\e[38;5;195m N\\e[38;5;11m ⭐ \\e[38;5;195m I\\e[38;5;11m ⭐ \\e[38;5;195m N\\e[38;5;11m ⭐ \\e[38;5;195m G !!!!!!!!!!!!"
#echo -e "\e[38;5;212m❤️️ ❤️️ ❤️️ ❤️️ ❤️️ \\e[38;5;9m❤️️ ❤️️ ❤️️ \\e[38;5;212m❤️️ ❤️️ ❤️️ ❤️️ ❤️️ \\e[38;5;190m❤️️ ❤️️ ❤️️ !!!!!!!!\\e[38;5;9m❤️️ \\e[38;5;212m❤️️ ❤️️ ❤️️ ❤️️ \\e[38;5;11m❤️️  \\e[38;5;190m"    

echo -e ""
#echo -e "\e[38;5;9m⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐⭐SUPER \\e[38;5;118mPENDING \\e[38;5;11m!!!!!!!!\\e[38;5;14m→ \\e[38;5;195m EL LOG DE LISTENIG ES OTRO, DONDE SE COPIA EL DICT TRANSCRIPT, Y LO EDITO, PARA EN EL FUTURO \\e[38;5;118m cmp dict.log lis.log \\e[38;5;195m Y REGISTRAR LO QUE CAMBIO!!!!!! "        

COLUMNS=12
echo -e "\e[38;5;195m 👉 velocity 🚨🚦🚨🚦🚨🚦🚨🚦🚨🚦🚨🚦 👉 👉 👉 👉  \e[38;5;118m${vlcspeed} \e[38;5;195m "
select golaudio in $(echo -e "${playlists[@]}")
do
	echo -e "\e[38;5;14m"  
	tail -1 ${playldir}/${golaudio} 
    if asksure; then
		SECONDS=0
		nvlc ${playldir}/${golaudio} 
		#FILE=${playldir}/${transcript} 

		logtime ${SECONDS}
		dtime=$(logtime ${SECONDS})
		#echo -e "TLOG ${golaudio} ✨ $(date +%D) → ${dtime}" > ${tlogfile}
		#echo -e "\e[38;5;195m TLOG \\e[38;5;14m»\\e[38;5;118m${golaudio} \\e[38;5;11m✨ \\e[38;5;195m $(date +%D) → ${dtime}" 
		#echo -e "\e[38;5;212mWrite a comment????"
		commentwork "${golaudio}" "${dtime}" "${tlogfile}"
		[[ -e "${tralogfile}" ]] && echo "💫 See typed transcript @ ${tralogfile} ⭐ ⭐ ⭐ " >> ${tlogfile}
	fi
	echo -e "\e[38;5;11m💫 \\e[38;5;118mAGUR!!!!!!!!!!!!!!!!\\e[38;5;11m 💫"
	exit
done
# ✨ 
