#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mpy ⇒ run, vim(PENDING) filecollections, pyfiles, oop-completebootcamp"
echo -e "	\\e[38;5;195m Run the py scripts en la file collection del Complete Bootcamp \\e[38;5;11m⭐\\e[38;5;195m porque no sé usar PYTHONPATH \\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 

function whichpyscr() {
	if [[ ! $1 ]]; then
	   tree ${PYTHONPATH} 
	   echo -e "\e[38;5;118m"
	   read -p "Select → " pyscr
	else
		pyscr=$1
	fi
}

##DIRECTORIES
##FILES
#VARIABLES
PYTHONPATH=/home/violeta/.filecollections_vio/pyfiles/oop-completebootcamp/
### MAIN
while getopts ":eh" o; do
    #gralGetops
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;;
		i)
			whichpyscr
			vim ${pyscr} 
			exit
			;;	
	esac
done
shift $((OPTIND-1))
# ♥

### MAIN
whichpyscr
python ${PYTHONPATH}/${pyscr}   
