#!/bin/bash

source Asksure.fu
source Opte.fu


function whatis() {
	cuseco=$(basename $0)
	echo -e "\e[38;5;118m${cuseco} ⇒  \e[38;5;11mtype:\e[38;5;118mvio-basadmin ⇒  gets pwd → select dir to cd and tree"
	echo -e "\e[38;5;195m Support para \e[38;5;11m⭐ alias \e[38;5;118m cres⭐ \e[38;5;195m as simple as \e[38;5;212m that ❤️️ 
	\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}
while getopts ":eh" o; do
	case "${o}" in
		e)
			opte
			exit
		;;
		h)
			whatis
			exit
		;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
		;;
	esac
done
shift $((OPTIND-1))


curdir=$(pwd)
select dir in $(find ${curdir} -type d -exec basename {} \;)
do
	cd ${dir}  
	tree ${curdir}/${dir} 
	break
done 
