#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\e[38;5;118m${cuseco}	→ \\e[38;5;11mtype:\\e[38;5;118mvio-basadmin → grep, vim » bin-scripts; "

	echo -e "\e[38;5;118m ⇒  \\e[38;5;195mAplica \\e[38;5;11mdefault show vio.sh help \\e[38;5;195mo lista de args \\e[38;5;11m\$@ \\e[38;5;195msi la hay, sobre los \\e[38;5;11m⭐ \\e[38;5;195mmy bin scripts \\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o 
	\e[38;5;212mUN-aliasED \\e[38;5;195mgrep [^-]type \\e[38;5;11m» \\e[38;5;118mgret \e[38;5;195m→ RUN gres \e[38;5;11m"the script" 
	\e[38;5;212mUN-aliasED \\e[38;5;195mshao | grep \\e[38;5;11m» \\e[38;5;118mgres \e[38;5;195m→ RUN gres \e[38;5;11m"the script" 
	"
}

## SOURCES 'S
##VARS-FILES 'B
##FUNCTIONS 'F
source Opte.fu
source Asksure.fu
##DIRECTORIES 'D
curdir=$(pwd)
bindir="/home/violeta/bin"
##FILES 'I
tmpfileSHOW="/home/violeta/bin/gresSHOW.tmp"
tmpfile="/home/violeta/bin/gres.tmp"

#VARIABLES 'V

while getopts ":eh" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1))

### MAIN
if [[ ! $1 ]]; then
	whattodo="\"\$l\" -h"
else
	whattodo="$@"
fi
find ${bindir} -maxdepth 1 -type f -executable -exec basename {} \; >| ${tmpfileSHOW}  
find ${bindir} -maxdepth 1 -type f -executable >| ${tmpfile}
while read -r l
do 
	if [[ ! $1 ]]; then
		$l -h
	else
		fipa=$(grep "$l" ${tmpfile})
		whattodo="$@"
#		echo -e "\e[38;5;11m INIT HERE \e[0m "
		if [[ ${whattodo} =~ "grep" ]]; then
			todo=$(${whattodo} ${fipa} )
			[[ ${todo} ]] && echo -en "\e[38;5;195m ⭐⭐⭐ $l " && echo -e "\\e[38;5;118m" && ${todo}  
		else
			${whattodo} ${fipa}
		fi
	fi
done < ${tmpfileSHOW}  

rm ${tmpfileSHOW}  ${tmpfile}
