#!/bin/bash
function whatis() {
	cuseco=$(basename $0)
	echo -e "\e[38;5;118m${cuseco} ⇒  \e[38;5;11mtype:\e[38;5;118mvio-helper ⇒  sed .bash_aliases vim emptypru/sh"
	echo -e "\e[38;5;195m para \e[38;5;11m⭐ fast vim \e[38;5;11m⭐ \e[38;5;195m del sh of the day \e[38;5;212m siempre desde emptypru ❤️️ 
	\e[38;5;118m★ \e[38;5;9moption option \e[38;5;195mquehace 🚁  
	\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
	return 25
}


## SOURCES 
##VARS-FILES
source Asksure.fu
source Opte.fu
source Continua.fu
source Echocolors.fu # black red green yellow blue magenta cyan white pink orange whiteguay @+N
##FUNCTIONS
##DIRECTORIES 
emptypru="/home/violeta/pruebas/emptypru"
##FILES
alisfile="/home/violeta/.bash_aliases"
nowsh="${emptypru}/$(grep "nowsh=" ${alisfile} | sed -ne 's/.*=//p')"
#VARIABLES

while getopts ":eh" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis 2>/dev/null
			[[ "$?" == 25  ]] || echo -e "PENDING whatis!! 🔥 "
			;; 
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1))
### MAIN
if [[ $1 ]]
then
	nowsh=$1 
	echo -e "\e[38;5;190m👉 nowsh\e[38;5;228m=\e[38;5;190m${nowsh} \e[38;5;11m??? \e[0m"     
	continua
	sed -i "s/nowsh=.*/nowsh=${nowsh}/" ${alisfile}
 	echo -e "Type \e[38;5;218msal 💕 " 	
else
	vim ${nowsh} 
fi	
