#!/bin/bash

source Asksure.fu
source Opte.fu

inmediately=false
while getopts ":ehi" o; do
    case "${o}" in  
        e)
            opte
            exit
            ;;
        h)
#            whatis
			echo -e "PENDING!! 🔥 "
			exit
			;;
		i)
			inmediately=true
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
    esac
done
shift $((OPTIND-1))

#MAIN
echo "get sudo 💥 eginda → "
sudo 2>/dev/null


if [[ ${inmediately} = false ]]; then 
	port22-abiertoono casipi
	[[ $? == 0 ]] && echo "open!!!" && ssh pi@casipi "sudo /sbin/shutdown -hP now"  || echo "closed!!" 
fi

sudo shutdown -h now
