#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mgit ⇒  add, commit, push pigit"
echo -e "	\\e[38;5;195m automating work @ \\e[38;5;11m⭐\\e[38;5;195m pigit!!!!!!!!!!!!! \\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
#VARIABLES

### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))
 
echo -e "⭐ \e[38;5;209mCommit all ⭐??????"
if asksure; then
	git add .
else
	echo -e "\e[38;5;195m " 
	read -p "Enter the files, then → " dfiles
	git add ${dfiles} 
fi

echo -e "\e[38;5;118m" 
read -p "Commit mess → " dmess
git commit -m "${dmess}"

git push pigit
