#!/bin/bash

source Asksure.fu
source Opte.fu
source Continua.fu

function whatis() {
	cuseco=$(basename $0)
	echo -e "\e[38;5;118m${cuseco} ⇒  \e[38;5;11mtype:\e[38;5;118mvio-helpers ⇒  for mp4 in cat vlc"
	echo -e "\e[38;5;195m coge una lista con names of mp4s \e[38;5;11m⭐ y la vlcea \e[38;5;11m⭐ \e[38;5;195m sin más opciones \e[38;5;212m de momento ❤️️ 
	\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

while getopts ":eh" o; do
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis
#			echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))

#MAIN
if [[ ! $1 ]]; then
	read -p "enter file con mp4 names → " mp4listfile
fi

for mp4 in $(cat ${mp4listfile})
do
	vlc ${mp4}  
done	
