#!/bin/bash

source Asksure.fu
source Opte.fu
source Continua.fu
source Echocolors.fu # black red green yellow blue magenta cyan white pink orange whiteguay @+N

# norminette -R CheckForbiddenSourceHeader cfile | tee cfile_nor

function whatis() {
	cuseco=$(basename $0)
	echo -e "\033[38;5;118m${cuseco} ⇒  \033[38;5;11mtype:\033[38;5;118mvio-urdu-help ⇒  norminette sed perl tr? vim"
	echo -e "\033[38;5;195m distintas funciones: \033[38;5;11m⭐ putas_tabs vim_cada_uno normi_cada_uno script_sed_all \033[38;5;11m⭐ \033[38;5;195m para respectivos trabajos \033[38;5;212m para usar a la vez en dos terminales ❤️️ 
	\033[38;5;43m\t👉\t\033[38;5;11moptions → \033[38;5;190m 
\033[38;5;11m★ \033[38;5;190m v \033[38;5;11m→ \033[38;5;118mvim
\033[38;5;11m★ \033[38;5;190m s \033[38;5;11m→ \033[38;5;118msed -i '' -f
\033[38;5;11m★ \033[38;5;190m n \033[38;5;11m→ \033[38;5;118mnorminette \033[38;5;228m(en \033[38;5;218mwhile \033[38;5;228mloop)   
\033[38;5;11m★ \033[38;5;190m t \033[38;5;11m→ \033[38;5;118medit tabs con perl...
	\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
	return 25
}

normised="/Users/viogonza/violetapiscina/urdubin/auxiliaries/aproespecific/normiscript.sed"

vimo=false
sedo=false
normo=false
ptab=false

func=""

dopts=( ${vimo} ${sedo} ${normo} )   

while getopts ":ehivsnt" o; do
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis 2>/dev/null
			[[ "$?" == 25  ]] || echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		v)
			vimo=true
			func=vim_cada_uno
			;;
		s)
			sedo=true
			func=script_sed_all 
			;;
		n)
			normo=true
			func=normi_cada_uno
			;;
		t)
			ptab=true
			func=putas_tabs
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))

function putas_tabs() {
	for rpcf in $(find . -type d -name "ex*" -exec realpath {} \; | sort -V ) 
	do
		cf=$(ls ${rpcf})
		vCFILE="${rpcf}/${cf}"
		vCFILEtmp="${vCFILE}.pttmp"
		echo ${vCFILE}  
		
		sed -i '' -f ${normised} ${vCFILE}
		
		expand -t 4 ${vCFILE} >| ${vCFILEtmp}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^void */void\t/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^char */char\t/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^int /*int\t/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^ {16}/\t\t\t\t/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^ {12}/\t\t\t/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^ {8}/\t\t/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^ {4}/\t/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/^ {1,3}//" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/[[:space:]]{4}/\t/" >| ${vCFILE}
#		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/[[:space:]]{2,3}/ /" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/int[[:blank:]]{2,}=/int =/" >| ${vCFILE}
		cat ${vCFILEtmp} | grep -v "^\/\*" | perl -pe "s/char[[:blank:]]{2,}=/char =/" >| ${vCFILE}

		echo -e "\033[38;5;218m" 
		cat -eT ${vCFILE}
		if asksure; then
			unexpand -t 4  ${vCFILE} >| ${vCFILEtmp}
			cat -eT ${vCFILEtmp}
			mv ${vCFILEtmp} ${vCFILE}
			vim -c "Stdheader" -c wq ${vCFILE}
			clear
		else
			exit
		fi
	done
}	


#for cf in $(find . -type f -name "*\.c")
function vim_cada_uno() {
	for rpcf in $(find . -type d -name "ex*" -exec realpath {} \; | sort -V ) 
	do
		cf=$(ls ${rpcf})
		vCFILE="${rpcf}/${cf}"
		echo ${vCFILE}  
		vim ${vCFILE} 
		continua
	done
}

function normi_cada_uno() {
	for rpcf in $(find . -type d -name "ex*" -exec realpath {} \; | sort -V )
	do
		this=true
		cf=$(ls ${rpcf})
		vCFILE="${rpcf}/${cf}"
		echo ${vCFILE}  
		while [ "${this}" = true ]
		do
			clear
			norminette -R CheckForbiddenSourceHeader ${vCFILE} | tee ${cf%.c}.norm
			echo -e "\033[38;5;190m D✨NG\033[38;5;228m??????????"  
			if asksure; then
				this=false
			fi
		done
	done	
}

function script_sed_all() {
	for rpcf in $(find . -type d -name "ex*" -exec realpath {} \; | sort -V )
	do
		cf=$(ls ${rpcf})
		vCFILE="${rpcf}/${cf}"
		echo ${vCFILE}  
		sed -i '' -f ${normised} ${vCFILE} && cat -eT ${vCFILE} && continua
	done
}
		
[[ ${func} = "" ]] && echo "hola!" || ${func}  
#script_sed_all
#normi_cada_uno
#vim_cada_uno
