#!/bin/bash

source Asksure.fu
source Opte.fu
source Continua.fu
source Echocolors.fu # black red green yellow blue magenta cyan white pink orange whiteguay @+N

#for d in "jperezc4" "mvalientc05" "isojoC05" "eescubidubiduC05" "ghurtado06" "alejarodc06"
allcfiles= ( "ft_strlen.c" "ft_putnbr.c" "ft_putstr.c" "ft_atoi.c" "ft_atoi_base.c" "ft_putnbr_base.c" "ft_is_prime.c" "ft_find_next_prime.c" "ft_fibonacci.c" "ft_iterative_power.c" "ft_iterative_factorial.c" "ft_print_params.c" "ft_print_program_name.c" "ft_recursive_factorial.c" "ft_recursive_power.c" "ft_rev_params.c" "ft_sort_params.c" "ft_sqrt.c" "ft_ten_queens_puzzle.c" )

cfiles4=( "ft_strlen.c" "ft_putnbr.c" "ft_putstr.c" "ft_atoi.c" "ft_atoi_base.c" "ft_putnbr_base.c" )
cfiles5=( "ft_iterative_factorial.c" "ft_recursive_factorial.c" "ft_iterative_power.c" "ft_recursive_power.c" "ft_fibonacci.c" "ft_sqrt.c" "ft_is_prime.c" "ft_find_next_prime.c" "ft_ten_queens_puzzle.c" )
cfiles6=( "ft_print_params.c" "ft_rev_params.c" "ft_sort_params.c" "ft_print_program_name.c" )

for cfile in ${cfiles5[@]}  
do
	versions="versions.${fn}"
#	[[ -e ${versions} ]] && rm ${versions}   
	vim -c "set nonumber" ${versions}  
#	find  . -name ${fn} -exec cat {} > ${versions} \;
#   tree ${d} 
	continua   
done
