#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mbin work ⇒  mv → /bin"
echo -e " \e[38;5;195m sends cprue/sh files to BIN without .sh \\e[38;5;212m ❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m\\n
    "
}

#VARIABLES
jit=false

##DIRECTORIES
bindir=/home/violeta/bin
jitdir=/home/violeta/bin/jithelpers
##FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu
#gralgetops

### MAIN
while getopts ":ehj" o; do
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis 2>/dev/null
			[[ "$?" == 25  ]] || echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		j)
			jit=true
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))
# ♥

dshfile=$1
dfile=$(realpath ${dshfile}) 

if [[ ${jit} = true ]]; then
	outdir=${jitdir}
else
	outdir=${bindir}     
fi

mv ${dfile} ${outdir}/${dshfile%.sh} 

ls ${outdir}  
