#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\\e[38;5;118m${cuseco}	→ \\e[38;5;11mtype:\\e[38;5;118mvio-bas-admin: ls clog maestro"
	echo -e "\\e[38;5;118m ⇒  \\\e[38;5;195mLee la señal de \\e[38;5;228mtrue \\e[38;5;195m→ ls current log.maestro 
	\e[38;5;11m» con \\e[38;5;9mv option \\e[38;5;195m, aliasado a \\e[38;5;118mclomanov\\e[38;5;195m, le hace vim
	\e[38;5;11m» con \\e[38;5;9mo option \\e[38;5;195m, aliasado a \\e[38;5;118mclomano \\e[38;5;195m, hace un select para vim other than el maestro now
\e[38;5;11m⭐\\e[38;5;195m he aprendido que una variable que se crea en un alias, no es accesible por el mismo alias \\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

## SOURCES 'S
##VARS-FILES 'B
##FUNCTIONS 'F
source Opte.fu
source Asksure.fu
##DIRECTORIES 'D
##FILES 'I
#VARIABLES 'V
vimit=false
othi=false

while getopts ":ehvo" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; # 'O
		v) 
			vimit=true
			;;
		o)
			othi=true
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN 
wmaf=`sed -ne "25,32p" /home/violeta/.bashrc | grep true | sed -ne "s/=true//p"`
if [[ $wmaf =~ "ystpelectricity" ]]; then
	wmaf='ystp-electricity'
elif [[ $wmaf =~ "docspersonalesyrepasos" ]]; then
	wmaf='docs-personales-y-repasos'
elif [[ $wmaf =~ "extendother" ]]; then 
	wmaf='extend-other'
fi

if [[ ${othi} = true ]]; then
	select wmaf in $(find /home/violeta/.clogs/maestros -name "*.log.maestro" -exec basename {} \; )
	do
		vim /home/violeta/.clogs/maestros/$wmaf
		break
	done
	exit
fi	

if [[ ${vimit} = true ]]; then
    vim /home/violeta/.clogs/maestros/$wmaf.log.maestro
else
	ls /home/violeta/.clogs/maestros/$wmaf.log.maestro
fi
