#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mvio-basadmin → vim -c alis file"
echo -e "	\\e[38;5;195m Create an alias from given \$1 \\e[38;5;11m⭐\\e[38;5;195m ol'ea \\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;9m!!! \\e[38;5;195m If there is a \\e[38;5;118mSECOND ARG and it is NUMERIC \\e[38;5;195m the new ali is inserterd bellow \\e[38;5;118mDAT \\e[38;5;195m line nummber\\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} toal \\n \\e[38;5;195m  alis \\e[38;5;11m → \\e[38;5;208m alias toal=what I write\\n\\e[38;5;11m${cuseco} toal 71219 \\n \\e[38;5;195m  alis \\e[38;5;11m → \\e[38;5;208m alias \\e[38;5;118m71219\\e[38;5;11m: \\e[38;5;208mtoal=what I write\e[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
alisfile=/home/violeta/.bash_aliases
#VARIABLES
toal=$1
ln=$2
#catout='' 
### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))

#cat >> /home/violeta/.bash_aliases
read dcom
echo -e "\e[38;5;11m ⭐\\e[38;5;208malias \\e[38;5;195m ${toal}\\e[38;5;208m='\\e[38;5;195m ${dcom}\\e[38;5;208m' \\e[38;5;118m????????"

if asksure; then
	echo -e "alias ${toal}='${dcom}'" >> ${alisfile}
	if [[ ${2} ]]; then
		vim -c ":\$m${ln} | write | quit" ${alisfile} 
	fi	
	source ${alisfile}
	echo -e "\e[38;5;11mD✨NG!!!! \e[0m" 
fi
