#!/bin/bash

function whatis() {
	cuseco=$(basename $0) 
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mgrep ⇒  find, xargs, grep in DEBIAN USR LOCAL"
echo -e "	\\e[38;5;195m GREP IN DEBIAN USR LOCAL \\e[38;5;11m⭐\\e[38;5;195m I miss my scripts :( \\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} hola\e[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
dul="/home/violeta/.dcopies_prev_installations/dusrlocbin"
##FILES
scrf=scrs.tmp
#VARIABLES
dterm=$1
### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))

[[ ! $1 ]] && echo -e "\e[38;5;118m pero qué término??? \e[0m" && exit  

find ${dul} -type f | xargs grep -I ${dterm} | tee ${scrf} #| less
scrar=()
for f in $(cat ${scrf})
do
	scrar+=($f) 
done	
