#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\\e[38;5;118m${cuseco}	→ \\e[38;5;11mtype:\\e[38;5;118mvio-workflow: grep \\e[38;5;11marg \\e[38;5;118min finded files named \\e[38;5;11mregex\\e[38;5;118m, \\e[38;5;9mexclude \\e[38;5;118min path \\e[38;5;11mregex \\e[38;5;118mand \\e[38;5;208m select \\e[38;5;118mto \\e[38;5;195mvim    \e[0m"   
	echo -e "\\e[38;5;118m ⇒  \\\e[38;5;195mFind files by given name \\e[38;5;195min here unless \\e[38;5;9m4th arg \\e[38;5;195m.
	\e[38;5;118mH A S T A ⭐ ⭐ ⭐  3  A R G S  S E P A R A D O S  P O R \\e[38;5;9m'\\e[38;5;208m,\\e[38;5;9m' 
	\e[38;5;118mTambién hay \\e[38;5;9mn option \\e[38;5;118mpara ver el line number con match"  
}

## SOURCES 'S
##VARS-FILES 'B
##FUNCTIONS 'F
source Opte.fu
source Asksure.fu

function tmpfile() {
	res=$1
	if [[ -f ${res} ]]; then
		rm ${res} 
	fi   
}


##DIRECTORIES 'D
curdir='.'
##FILES 'I
#VARIABLES 'V
grepco=grep
selvim=()
res="result.ffg"

while getopts ":ehn" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; # 'O
		n)
			grepco="grep -n"
			;;

		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN 'M
#findthis=$1
#grepthis=${@: 2}
#
#[[ ${otherdir} = true ]] && read -p "Find dir: " fdir || fdir=${curdir}   
#for f in $(find ${fdir} -name "${findthis}" )
#do
#	[[ $(grep "${grepthis}" "$f" 2>/dev/null ) ]]  && ls "$f"
#done

# hay que grep in directories/files → hay que grepthis en wherethis if notthis 
allargs="$@"
[[ ${allargs} == "" ]] && echo -e "\e[38;5;195mGrep what??" && exit 

IFS=',' read -ra ARGS <<< "${allargs}"
let count=0
for i in "${ARGS[@]}"; do
	let count+=1
	[[ ${count} -eq 1 ]] && continue 
	[[ ${count} -eq 2 ]] && grepthis="${i}"
	[[ ${count} -eq 3 ]] && fileregex="${i}" 
	[[ ${count} -eq 4 ]] && notthis="${i}" || notthis="bupREGEX-tomakethiswork"
done

if [[ ${notthis}  =~ " " ]]; then 
	notthis=$(echo ${notthis} | tr " " '\|')
fi

echo -e "\e[38;5;118mgrep \\e[38;5;195m${grepthis}\\e[38;5;118m in files=~\\e[38;5;195m${fileregex} \\e[38;5;9mnot \\e[38;5;195m${notthis} \n" 	

#echo -e "\e[38;5;195m${grepthis}"
#echo -e "\e[38;5;195m${wherethis}"
#echo -e "\e[38;5;195m${notthis}"
#exit



tmpfile ${res}  
wherethis=$(find . -type f -name "${fileregex}")

let resn=0
for f in ${wherethis}
do
	let resn+=1 
	if [[  $(grep "${grepthis}" "${f}" 2>/dev/null )  &&  ! "${f}" =~ ${notthis} ]]
	then
	   selvim+="${f} "  
	   echo -e "\\e[38;5;11mfile::\\e[38;5;118m${f} \\\e[38;5;195m " >> ${res} 
	   ${grepco}  "${grepthis}" "${f}" 2>/dev/null  | sort | uniq >> ${res} 
	fi
done	

cat ${res}  
echo -e "\n💥 Select and vim??????"
if asksure; then
	echo -e "\e[38;5;195m" 
	select f in $(echo "${selvim[@]}")
	do
		vim $f
		break
	done
fi
tmpfile ${res}  
