#!/bin/bash

source Asksure.fu
source Opte.fu
source Continua.fu

cuseco=$(basename $0)
function miniwhatis() {
   	echo -e "\e[38;5;11m ★ \e[38;5;190m$1 \e[38;5;118m takes arguments \e[38;5;195m⇒  \e[38;5;218mlo que se quiere copiar\e[38;5;208m; \e[38;5;228mdespués \e[38;5;208mel programa pregunta que \e[38;5;118ma dónde"
}
function whatis() {
	cuseco=$(basename $0)
	echo -e "\e[38;5;118m${cuseco} ⇒  \e[38;5;11mtype:\e[38;5;118mvio-helper ⇒  scp macasi"
	miniwhatis ${cuseco}  
	echo -e "⭐ ⭐ \e[38;5;195m asumo que hoss\e[38;5;118m √ \e[38;5;228m(que \e[38;5;195mIP \e[38;5;118m√ \e[38;5;228m)\e[38;5;212m and go ❤️️ 
	\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
	return 25
}

while getopts ":eh" o; do
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis 2>/dev/null
			[[ "$?" == 25  ]] || echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))

baseto="violetagonzalezgarcia@macasi:/Users/violetagonzalezgarcia/"
whatto=$@
[[ ${whatto} = "" ]] && miniwhatis ${cuseco} && exit 
read -p "Now type the remainder path → /Users/violetagonzalezgarcia/ » " whereto 

scp ${whatto} ${baseto}${whereto}    
[[ $? != 0 ]] && echo "merde; a veces hay que hacerlo dos veces para que vaya"
