#!/bin/bash

function whatis() {
	echo -e "$0"
	echo -e "\e[38;5;118mtype:\\e[38;5;195mvio-basadmin: mv \$@ to /emptypru"
	echo -e "Con \e[38;5;9mc option \e[38;5;195mcp instead
  	\e[38;5;43m\t \t👉\tp  \\e[38;5;228m\$1"
}
source Asksure.fu
source Opte.fu

what="mv"
dir="/home/violeta/pruebas/emptypru"

while getopts ":ehcd:" o; do 
	case "${o}" in 
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;;
		c)
			what="cp"
			;;
		d) 
			dir=$OPTARG
			;;
		?)
			echo -e "Nein nein nein $o option "
			exit
			;;
	esac
done
shift $((OPTIND-1))

# ♥
 

dfiles=$@
${what} ${dfiles} ${dir}
