#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\e[38;5;11mtype:\e[38;5;118mpdftk → find, pdftk, grep, awk ⇒  get number of pages"
echo -e "	\e[38;5;195m ENCONSTRUCCIÓN \e[38;5;11m⭐\e[38;5;195m ALGOESTRELLADO \e[38;5;11m⭐\e[38;5;195m \e[38;5;212m❤️️ \n\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
#VARIABLES

### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))

if [[ $1 ]]; then
	pdf=$1
else
	pdf="*.pdf"
fi

find . -name "${pdf}" -exec pdftk {} dump_data output \; | grep NumberOfPages | awk '{s+=$2} END {print s}'
