#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
	echo -e "\e[38;5;118m${cuseco} ⇒  \e[38;5;11mtype:\e[38;5;118mvio-helper ⇒  for find echo grep sed basename mkdir mv"
	echo -e "\e[38;5;195m para files que no son: \e[38;5;11m⭐ md mp4 jpg png pdf html ...  \e[38;5;9mopt a \e[38;5;195mpara a;adir m'as   \e[38;5;11m⭐ \e[38;5;195m los copio en pruebas, mirroring cifo \e[38;5;212m y a ver si hugo funciona ahora!!!! ❤️️ 
	\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

source Asksure.fu
source Opte.fu
source Continua.fu

addnotthis=false

while getopts ":eha" o; do
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis
			#echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		a)
			addnotthis=true
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))

echo -e "cubierta de gloria, borré todo lo que queria salvar"
exit

thisfile=$0
bbdir="/home/violeta/PROYECTO/estudios/instalacionfotovoltaica"
bupibup="/home/violeta/pruebas/bupibup"
#[[ -d ${bupibup} ]] && rm -rf ${bupibup} 
#mkdir ${bupibup}

function check() {
	echo -e "\e[38;5;118m${emd} \e[38;5;228m→ ${firstline}" && continua 
}

notthese='! -name "\*md" ! -name "\*mp4" ! -name "\*jpg" ! -name "\*png" ! -name "\*pdf"  ! -name "\*html" ! -name "\*toml"'

[[ ${addnotthis} = true ]] && read -p "enter extension → " ext && notthese="${notthese} ! -name \"\*${ext}\"" && echo ${notthese} && continua && sed -i "s/^notthese=.*/notthese=\'${notthese} ! -name \"\*${ext}\"\'/" ${thisfile}   

set -x
for i in $(find . -type f  ${notthese} | grep -v md) 
do
	tocop=$(echo $i | sed -ne "s?^.?${bupibup}?p")
	dfile=$(basename ${tocop})	
	ddir=$(echo ${tocop} | sed -ne "s?/${dfile}??p")
    [[ ! -d ${ddir} ]] && mkdir -p ${ddir} 
	echo -e "mv ${i} ${ddir} ?????????????????????"
	continua
    mv ${i} ${ddir}   	
done


#let count=0
#for md in $(find . -name "*md" )
#do
#	let count=${count}+1 
##	echo -e "\e[38;5;118m" &&  ls ${mdd} && echo -e "→ \e[38;5;228m " 
#	firstline=$(sed -ne "1p" ${md})
#	emd=$(echo ${md} | sed -ne "s/..\(.*\)/\1/p") 
#	if [[ ${firstline} =~ "+++" ]]; then
#	   check
#	   sed -i "s/+++/---/" ${md} 
#	   sed -i "/---/,/---/s/ =/:/" ${md} 
#	   firstline=$(sed -ne "1p" ${md})
#	   check 
#    elif [[ ! ${firstline} =~ "---" ]]; then
#	   check
#	   mv ${md} ${md%md}.pendinghnew
#	   $(cd ${bbdir} ; hugo new ${emd} 2>/dev/null ) 2>/dev/null 
#	   cat ${md%md}.pendinghnew >> ${emd}  
#	   notthis=$(echo ${emd}) 
#    else
#		echo -e "\e[38;5;118m${emd} \e[38;5;208m⇒ \e[38;5;228m→ ${firstline} » \e[38;5;118m √  " 
#	fi   
#	[[ $(grep "draft" ${md}) && ${md} != ${notthis} ]] && vim ${md}   
#done   
