#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
	echo -e "\e[38;5;118m${cuseco} ⇒  \e[38;5;11mtype:\e[38;5;118mvio-helper ⇒  read newname cp plantillas-folder"
	echo -e "\e[38;5;195mCada \e[38;5;11m⭐ s.sh \e[38;5;11m⭐ \e[38;5;195m si me parece reutilizable: \e[38;5;212m la guardo como plantilla ❤️️ 
	\e[38;5;118m★ \e[38;5;9moption r \e[38;5;195mretocar \e[38;5;9m(\e[38;5;195mantes de guardar\e[38;5;9m) 🚁  
\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -r\e[0m"
	return 25
}


## SOURCES 
##VARS-FILES
source Asksure.fu
source Opte.fu
source Continua.fu
source Echocolors.fu # black red green yellow blue magenta cyan white pink orange whiteguay @+N
##FUNCTIONS

##DIRECTORIES 
curdir=$(pwd)
plantillasdir="/home/violeta/pruebas/plantillaSH"
##FILES
dfile="s.sh"
#VARIABLES
datevar=$(date +%m%d-%Hh%Mm)

while getopts ":ehr" o; do 
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		r)
			vim s.sh
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1))

### MAIN
echo -e "\e[38;5;14mNombre descriptivo de la plantilla (espacios \e[38;5;190m√ \e[38;5;14m; sin \e[38;5;228mext\e[38;5;14m) \e[38;5;195m" 
read -p "Nombre → " desc
set -x
desc=$(echo ${desc} | sed -ne "s/ /_/gp")
desc=${desc}-${datevar}.sh  
echo -e "\e[38;5;190m ${desc} \e[38;5;228m??"
continua
mv ${dfile} ${plantillasdir}/${desc}  
tree ${plantillasdir}  
