#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mvio-basadmin → select, vim , mv, cp, vlc ; improved para git → out vers-his, .git"
echo -e "	\\e[38;5;195m SELECT \\e[38;5;11mfile as default \\e[38;5;195m from \\e[38;5;11mhere as default \\e[38;5;195m by name \\e[38;5;11mas default \\e[38;5;11m⭐\\e[38;5;195m and \\e[38;5;9mVIM\\e[38;5;195m it \\e[38;5;11m(as default)\\e[38;5;195m !!! \\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} TERM* \\n \\e[38;5;195m ... per sigo investgando cómo hacerlo bien, para excluya paths sin grep -v...
💥 \e[38;5;118m recuerda meter findterm\e[38;5;11m!!!\e[38;5;118m este select funciona dándole un parámetro name que acote el find\e[38;5;11m!! \e[38;5;118m:( NO vale el \e[38;5;11m'\e[38;5;118m*\e[38;5;11m' a secas 💥💥💥💥💥 \e[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu

function getwhereto() {
	echo -e "💫\e[38;5;118m where or what to \\e[38;5;11m?????"	
	read where 
}

##DIRECTORIES
ddir=$(pwd)
##FILES 
#VARIABLES

what=vim
whereto=false
findterm=$1
cleanit=false

while getopts ":ehwvo" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		w)
			echo -e "\e[38;5;14m" 
			findterm=$2 #NOTA ⇒  con la expansión * al lanzar selvv, si findterm es $2, solo me coje el segundo, y no toda la expansión
			[[ ${@: -1} =~ "-" ]] && what=$(echo ${@: -1} | sed -ne 's/-//p') && set -- "${@:1:$(($#-1))}" || read -p " whaaaatt?? → " what
			;;
		v)	echo -e "\e[38;5;14m" 
			findterm=$2 #NOTA ⇒  con la expansión * al lanzar selvv, si findterm es $2, solo me coje el segundo, y no toda la expansión
			what=vlc
			cleanit=true
			;;
		o)
			findterm=$2
			read -p "default cat or enter command → " what
			[[ ${what} == "" ]] && what=cat 
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1))

### MAIN
if [[ ${@: -1} == "m" || ${@: -1} == "c" ]]; then
	whereto=true
	findopts=${@: -2}
	echo -e "findopts → ${findopts} " 
	[[ ${@: -1} == "m" ]] && what="mv" || what="cp -r"
else
	# ATT si tengo problemas pueden estar aquí, porque ... no sé por qué pero en algún edit el caso es que dejé la var inutilizable as findopts=${@: }; la retoco a ojo a findopts=${@}, pero queda este aviso si un día algo no va... como esperaría que fuera
	findopts=$(echo ${@} | grep -v "/home/violeta/selvv") # AQUÍ está la expansión de un findterm con regex: findterm*
#	echo "yeah yeah AQUÍ está la expansión findterm*"
fi

if [[ ${findopts} == "" ]]
then
	findopts=" ${ddir} -type f -name "
fi

COLUMNS=12
findhere=$(find ${findopts} ${findterm} | grep -v "version-history" | grep -v "\.git")
select f in ${findhere}  
#select f in $(find ${findopts} ${findterm} | grep -v "version-history" | grep -v "\.git") 
do
	if [[ ${whereto} == true ]]; then
		getwhereto
		${what} ${f} ${where} 
    else
	 	${what} ${f}  
	fi  
	[[ ${cleanit} = true ]] && clear && REPLY=""
#	break
done
