#!/bin/bash

source Opte.fu
function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mvio-basadmin → awk, bash-arrays"
echo -e " "  
			echo -e "\e[38;5;43mUsage: \\e[38;5;118mvawk \$delimiter \$comma-separated-list-of-fields"
			echo -e "\e[38;5;195m Es un awk con el given delimiter, que printa los given fields"
			echo -e "\t\t👉\t[38;5;212m$ vawk : 2,3 afile"
			echo -e "\e[38;5;195m awk -F\$del \"BEGIN{OFS=\"\\t\"; print OFS}{print \$fields}\" \$file	 | sort | uniq"
			echo -e "\e[0m"
}

while getopts ":eh" o; do 
	case "${o}" in 
		e)
			opte
			exit
			;;
		h)
			exit
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))



del=$1
if [[ $1 == e ]]; then
	del=" "
fi

_file=${@: -1}
length=$(( $# - 1 ))

if [[ -f $_file ]]; then
	file=$_file
	forfields=${@:2: length -1}
else
	forfields=${@:2: length}
fi

for f in $forfields
do
	fields=$(echo -ne "${fields} \$${f}")
done

#echo -e "del: $del\n_file: $_file\nlength: $length\nfile= $file\nforfields: $forfields\nfields: $fields"
awk  -F"${del}" "BEGIN{OFS=\"\t\"; print OFS}{print ${fields}}" $file	 | sort | uniq
