#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\033[38;5;118m${cuseco} → \033[38;5;11mvio-helpers:\033[38;5;118mwhiptail for each item in file"
	echo -e "\033[38;5;118m⇒  \033[38;5;195mMuestra en una box cada linea del file \$1 
	⭐\033[38;5;9m no opt → \033[38;5;195myes or not \033[38;5;118m; \033[38;5;9mopt m → \033[38;5;195mmessage box a secas ⭐ ❤️️ 
\t\\033[38;5;43mFor example:
\t\\033[38;5;228m${cuseco} -m afile\033[0m"
}

## SOURCES 
##VARS-FILES
source Opte.fu
source Asksure.fu
##DIRECTORIES 
##FILES
dfile=${@: -1}
dfilereses="whiped.${dfile}.aux"
#VARIABLES
omesonly=false
func="bai ala ez"
##FUNCTIONS
function getanswers() {
  if [[ $1 == 0 ]]; then
	  echo "$2 → bai" | tee -a ${dfilereses}  
  else
	   echo "$2 → ez" | tee -a ${dfilereses}  
  fi
}
function yesno() {
  answer=$(whiptail --clear  --title "TO HELL AND BACK ⚡⚡⚡⚡⚡" --yesno "$1" 0 0 3>&1 1>&2 2>&3; echo $?)
  #	answer=$(whiptail --yesno "$1" 0 0 3>&1 1>&2 2>&3; echo $?)
  getanswers ${answer} ${1}   
}
function mesonly() {
  answer=$(whiptail --clear  --title "TO HELL AND BACK ⚡⚡⚡⚡⚡" --msgbox "$1" 0 0 3>&1 1>&2 2>&3; echo $?)
  getanswers ${answer} ${1}
}

while getopts ":ehm" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		m) 
			omesonly=true
			func="msgbox"
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN
[[ ! -e ${dfile} ]] && echo -e "no file!!" && exit

echo -e "# START: ${func} → ${dfile} » $(date) " >> ${dfilereses}

for esan in $(cat ${dfile})
do
	#yesno "$@"
	[[ ${omesonly} == true ]] && mesonly "${esan}" ||  yesno "${esan}"
done

echo -e "## END: ${func} → ${dfile} » $(date) " >> ${dfilereses}
