#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\033[38;5;118m${cuseco}	⇒ 	\\033[38;5;11mtype:\\033[38;5;118mvio-basadmin → select,  alis file, set working hugo site"
echo -e "	\\033[38;5;195m Cd a cualquier \\033[38;5;11m⭐\\033[38;5;195m proyecto hugado \\033[38;5;11m⭐\\033[38;5;195m \n\\033[38;5;118m${cuseco} \\033[38;5;195m lista los \\033[38;5;11mproyectos hugados \\033[38;5;195m cuyos \\033[38;5;208m cd alis \\033[38;5;195m y \\033[38;5;208mpaths \\033[38;5;195m se guardan en un file auxiliar, que se edita con la \\033[38;5;9mg\\033[38;5;195m opt \\033[38;5;118mPENDING! \\033[38;5;212m❤️️ \\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
alisfile="/Users/violetagonzalezgarcia/gitclones/.bash_aliases"
dhugositesfile="/Users/violetagonzalezgarcia/gitclones/bin/auxiliaries/aproespecific/hugo.sites"
#lista de proyectos hugados file...
#VARIABLES

### MAIN
while getopts ":ehs" o; do
	#TODO cdv-getops con g...
    # gralGetops #
	case ${o} in
		e)
			opte
			exit
			;;
		h)
            whatis
            exit
            ;;
		s)
			vim ${dhugositesfile} 
		    exit
			;;	
        \?)
            echo -e "Nein nein nein option → ${o}"
            exit
            ;;
    esac
done
shift $((OPTIND-1))

#TODO mejorar todo

if [[ $1 ]]
then
    site=$1
else
    #cdv -s
    echo "Choose SITE"
	dsites=()
	for i in $(cut -f 1 ${dhugositesfile}) #$(awk "{print}" ${dhugositesfile})
	do
		dsites+="${i} " 
	done	
	select site in $(echo "${dsites[@]}") #$(echo -e "\033[38;5;195m ${dsites[0]} \\033[38;5;118m${dsites[1]}" )
	do
		echo -e "\033[38;5;118m ${site} " 
		cp ${alisfile} /Users/violetagonzalezgarcia/gitclones/.bups_vio${alisfile#/home/violeta/}
		#todir=$(cat ${alisfile} | grep -I ${site}= | awk -F= '{print $2}' |  tr -d "'" | awk '{print $2}' | awk '{gsub("~","/home/violeta"); print}')
		sed -i '' "s/^alias bb=.*/alias bb=${site}/" ${alisfile}
		sed -i '' "/SEDSECTION/,/ENDOF-SEDSECTION/s/='[^;]*;/='${site} ;/" ${alisfile}
		break
	done
fi
	
#TODO cd ${todirPATH}
