#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\033[38;5;118m${cuseco}	⇒ 	\\033[38;5;11mtype:\\033[38;5;118mvio-basadmin → vim -c alis file"
echo -e "	\\033[38;5;195m Create an alias from given \$1 \\033[38;5;11m⭐\\033[38;5;195m ol'ea \\033[38;5;11m⭐\\033[38;5;195m \\033[38;5;212m❤️️ \\n\\033[38;5;9m!!! \\033[38;5;195m If there is a \\033[38;5;118mSECOND ARG and it is NUMERIC \\033[38;5;195m the new ali is inserterd bellow \\033[38;5;118mDAT \\033[38;5;195m line nummber\\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} toal \\n \\033[38;5;195m  alis \\033[38;5;11m → \\033[38;5;208m alias toal=what I write\\n\\033[38;5;11m${cuseco} toal 71219 \\n \\033[38;5;195m  alis \\033[38;5;11m → \\033[38;5;208m alias \\033[38;5;118m71219\\033[38;5;11m: \\033[38;5;208mtoal=what I write\033[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
alisfile=/Users/violetagonzalezgarcia/gitclones/.bash_aliases
#VARIABLES
toal=$1
ln=$2
#catout='' 
### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))

#cat >> /Users/violetagonzalezgarcia/gitclones/.bash_aliases
read dcom
echo -e "\033[38;5;11m ⭐\\033[38;5;208malias \\033[38;5;195m ${toal}\\033[38;5;208m='\\033[38;5;195m ${dcom}\\033[38;5;208m' \\033[38;5;118m????????"

if asksure; then
	echo -e "alias ${toal}='${dcom}'" >> ${alisfile}
	if [[ ${2} ]]; then
		vim -c ":\$m${ln} | write | quit" ${alisfile} 
	fi	
	source ${alisfile}
	echo -e "\033[38;5;11mD✨NG!!!! \033[0m" 
fi
