#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\033[38;5;118m${cuseco} → \033[38;5;11mtype:\033[38;5;118mvio-helper : greper cut sort uniq "
	echo -e "\033[38;5;118m⇒  \033[38;5;195mENCONSTRUCCIÓN → mejorar
	⭐\033[38;5;195m ALGOESTRELLADO ⭐ ❤️️ 
\t\\033[38;5;43mFor example:
\t\\033[38;5;228m${cuseco} -$o\033[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS
source Asksure.fu
source Opte.fu
source Continua.fu
 
##DIRECTORIES 
vpfile="/Users/violetagonzalezgarcia/gitclones/.persistent_history"
clogsdir="/Users/violetagonzalezgarcia/gitclones/.clogs"
##FILES
#VARIABLES
today=false
yesterday=false
rdate=$(date +%Y-%m-%d)
old=false

while getopts ":ehtyo" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		t)
			today=true
			;;
		y)
			yesterday=true
			;;
		o)
			old=true
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

togrep="$@"
### MAIN

if [[ ${old} = true ]]; then
	if [[ "${@: -1}" =~ [1-9][0-9]?[0-9]? ]]; then
		days=${@: -1}
		togrep=${@:1:$#-1}
	else 
		days=$(ls ${clogsdir} | wc -l )
	fi

	for clog in $(ls ${clogsdir}/*clog | tail -${days} ) 
	do
		grep -a ${togrep} ${clog}   
	done
	exit
fi

if [[ ${yesterday} = true ]]; then
	ym=$(echo $rdate | awk -F- '{printf("%d-0%d"),$1,$2}')
	dd=$(echo $rdate | awk -F- '{print $3}')
	let d=$dd-1
	rdate="${ym}-0${d}"
	echo $rdate
fi

if [[ ${yesterday} = true ]] || [[ ${today} = true ]]; then
	grep -a ${rdate} ${vpfile} >| "${vpfile}.tmp" 
	vpfile="${vpfile}.tmp" 
fi

tmpfile1=$(basename $0).tmp1

[[ -e ${tmpfile1} ]] && rm ${tmpfile1}   


grep -a ${togrep} ${vpfile}  | awk -F"|" '{print $2}' | awk '{gsub(/^[ \t]+|[ \t]+$/,""); print $0}' | sed "s/ \+/ /g" | sort | uniq > ${tmpfile1}  
cat ${tmpfile1}  

rm ${tmpfile1} 
[[ -e "${vpfile}.tmp" ]] && rm ${vpfile}.tmp
