#!/bin/bash

function whatis() {
	cuseco=$(basename $0) 
 echo -e "\033[38;5;118m${cuseco}	⇒ 	\\033[38;5;11mtype:\\033[38;5;118mgrep ⇒  find, xargs, grep in DEBIAN USR LOCAL"
echo -e "	\\033[38;5;195m GREP IN DEBIAN USR LOCAL \\033[38;5;11m⭐\\033[38;5;195m I miss my scripts :( \\033[38;5;11m⭐\\033[38;5;195m \\033[38;5;212m❤️️ \\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} hola\033[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
dul="/Users/violetagonzalezgarcia/gitclones/.dcopies_prev_installations/dusrlocbin"
##FILES
scrf=scrs.tmp
#VARIABLES
dterm=$1
### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))

[[ ! $1 ]] && echo -e "\033[38;5;118m pero qué término??? \033[0m" && exit  

find ${dul} -type f | xargs grep -I ${dterm} | tee ${scrf} #| less
scrar=()
for f in $(cat ${scrf})
do
	scrar+=($f) 
done	
