#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\033[38;5;118m${cuseco}	⇒ 	\\033[38;5;11mtype:\\033[38;5;118mgit ⇒  git add, commit and push; init repo \& add remote pigit if must"
echo -e "	\\033[38;5;195m Uses upi -- que contiene los basic add, commit, push  \\033[38;5;11m⭐\\033[38;5;195meste añade el init & add remote \\033[38;5;11m⭐\\033[38;5;195m \\033[38;5;212m❤️️ \\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
}

function donetodayandlooksgood() {
	echo -e "\033[38;5;14m
   ⚡ cd .viogit/
   ⚡ git init
   ⚡ for i in .bash_ali...
    do
	cp -r \$HOME/\$i .
	done
	⚡ git init
	⚡ upi
		→ git add .
		→ git commit -m \"mes\"
		→ git push pigit ⇒  ERR
	⚡ git remote add pigit git@casipi:/home/git/homedesktop.git
	⚡ git remote -v
pigit	git@casipi:/home/git/homedesktop.git/ (fetch)
pigit	git@casipi:/home/git/homedesktop.git/ (push)
	⚡ git push --set-upstream pigit master"
}

function los_echos_antes_de_func() {
echo -e "
\033[38;5;9m ⭐ THIS IS TEMP	⇒ 	see \\033[38;5;14mhttps://devconnected.com/how-to-remove-files-from-git-commit/  
\033[38;5;195m git	\\033[38;5;118madd .   
\033[38;5;195m git	\\033[38;5;118mcommint -m \"\"   
\033[38;5;195m git	\\033[38;5;118mstatus   
\033[38;5;195m git	\\033[38;5;118m push -u origin main 
\033[38;5;195m git	\\033[38;5;118mrestore --source=HEAD^ --staged  -- file-to-delete-from-commit
\033[38;5;195m git	\\033[38;5;118mreset HEAD file-to-del-from-repo → 
\033[38;5;195m → git	\\033[38;5;118mrm --cached d-previously-unstaged-file →  
\033[38;5;195m → git	\\033[38;5;118mcommit --amend"

echo -e "\033[38;5;14m  ⭐ ⭐ from GITHUB ⭐	⇒ 	
\033[38;5;208m …or create a new repository on the command line
\033[38;5;118mgit\\033[38;5;195m init
\033[38;5;118mgit\\033[38;5;195m add README.md
\033[38;5;118mgit\\033[38;5;195m commit -m "first commit"
\033[38;5;118mgit\\033[38;5;195m branch -M main
\033[38;5;118mgit\\033[38;5;195m remote add origin pi@casipi:/home/pi/\${dgitrepo}.git

\033[38;5;118mgit\\033[38;5;195m push -u origin main
\033[38;5;208m  …or push an existing repository from the command line
\033[38;5;118mgit\\033[38;5;195m remote add origin pi@casipi:/home/pi/\${dgitrepo}.git
\033[38;5;118mgit\\033[38;5;195m branch -M main
\033[38;5;118m git push -u origin main
"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
#VARIABLES

### MAIN
while getopts ":eh" o; do
	case "${o}" in 
		e)
			opte
			exit
			;;
		h)
			whatis 
			echo -e "\033[38;5;11m »  \\033[38;5;118mView los ol'echos??"
			if asksure; then
				los_echos_antes_de_func
			fi
			echo -e "\033[38;5;11m »  \\033[38;5;118mView moooree???"
			if asksure; then 
				donetodayandlooksgood
			fi	
			exit
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))

if [[ ! -d .git ]]; then
	git init
	gitrepo=$(pwd | xargs basename).git
	echo -e "\033[38;5;195m${gitrepo} \033[38;5;190m√ \033[38;5;195m??"
	if asksure; then
		echo -ne "\033[38;5;190m√\033[38;5;195m!!!!!\033[0m "
	else
		read -p "name of repo, pues → " gitrepo
	fi
	git remote add pigit git@casipi:/home/git/${gitrepo} 
	git remote -v
	git add .
	read -p "Commit mess → " cmess
	git commit -m "${cmess}"
	git commit --amend
    git push --set-upstream pigit master	
else
	git add .
	read -p "Commit mess → " cmess
	git commit -m "${cmess}"
	git commit --amend
	git push pigit master
fi
