#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\\033[38;5;118m${cuseco}	→ \\033[38;5;11mtype:\\033[38;5;118mvio-workflow: grep \\033[38;5;11marg \\033[38;5;118min finded files named \\033[38;5;11mregex\\033[38;5;118m, \\033[38;5;9mexclude \\033[38;5;118min path \\033[38;5;11mregex \\033[38;5;118mand \\033[38;5;208m select \\033[38;5;118mto \\033[38;5;195mvim    \033[0m"   
	echo -e "\\033[38;5;118m ⇒  \\\033[38;5;195mFind files by given name \\033[38;5;195min here unless \\033[38;5;9m4th arg \\033[38;5;195m.
	\033[38;5;118mH A S T A ⭐ ⭐ ⭐  3  A R G S  S E P A R A D O S  P O R \\033[38;5;9m'\\033[38;5;208m,\\033[38;5;9m' 
	\033[38;5;118mTambién hay \\033[38;5;9mn option \\033[38;5;118mpara ver el line number con match"  
}

## SOURCES 'S
##VARS-FILES 'B
##FUNCTIONS 'F
source Opte.fu
source Asksure.fu

function tmpfile() {
	res=$1
	if [[ -f ${res} ]]; then
		rm ${res} 
	fi   
}


##DIRECTORIES 'D
curdir='.'
##FILES 'I
#VARIABLES 'V
grepco=grep
selvim=()
res="result.ffg"

while getopts ":ehn" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; # 'O
		n)
			grepco="grep -n"
			;;

		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN 'M
#findthis=$1
#grepthis=${@: 2}
#
#[[ ${otherdir} = true ]] && read -p "Find dir: " fdir || fdir=${curdir}   
#for f in $(find ${fdir} -name "${findthis}" )
#do
#	[[ $(grep "${grepthis}" "$f" 2>/dev/null ) ]]  && ls "$f"
#done

# hay que grep in directories/files → hay que grepthis en wherethis if notthis 
allargs="$@"
[[ ${allargs} == "" ]] && echo -e "\033[38;5;195mGrep what??" && exit 

IFS=',' read -ra ARGS <<< "${allargs}"
let count=0
for i in "${ARGS[@]}"; do
	let count+=1
	[[ ${count} -eq 1 ]] && continue 
	[[ ${count} -eq 2 ]] && grepthis="${i}"
	[[ ${count} -eq 3 ]] && fileregex="${i}" 
	[[ ${count} -eq 4 ]] && notthis="${i}" || notthis="bupREGEX-tomakethiswork"
done

if [[ ${notthis}  =~ " " ]]; then 
	notthis=$(echo ${notthis} | tr " " '\|')
fi

echo -e "\033[38;5;118mgrep \\033[38;5;195m${grepthis}\\033[38;5;118m in files=~\\033[38;5;195m${fileregex} \\033[38;5;9mnot \\033[38;5;195m${notthis} \n" 	

#echo -e "\033[38;5;195m${grepthis}"
#echo -e "\033[38;5;195m${wherethis}"
#echo -e "\033[38;5;195m${notthis}"
#exit



tmpfile ${res}  
wherethis=$(find . -type f -name "${fileregex}")

let resn=0
for f in ${wherethis}
do
	let resn+=1 
	if [[  $(grep "${grepthis}" "${f}" 2>/dev/null )  &&  ! "${f}" =~ ${notthis} ]]
	then
	   selvim+="${f} "  
	   echo -e "\\033[38;5;11mfile::\\033[38;5;118m${f} \\\033[38;5;195m " >> ${res} 
	   ${grepco}  "${grepthis}" "${f}" 2>/dev/null  | sort | uniq >> ${res} 
	fi
done	

cat ${res}  
echo -e "\n💥 Select and vim??????"
if asksure; then
	echo -e "\033[38;5;195m" 
	select f in $(echo "${selvim[@]}")
	do
		vim $f
		break
	done
fi
tmpfile ${res}  
