#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\033[38;5;118m${cuseco} → \033[38;5;11mtype:\033[38;5;118mvio-helper: hugo new grep vim rm"
	echo -e "\033[38;5;118m⇒  \033[38;5;195mhugo creates md from \$1 \033[38;5;9mSÓLO en cifo!!! 
	⭐\033[38;5;195m y vim it \033[38;5;208m unless \033[38;5;9mo opt  ⭐ ❤️️ 
\t\\033[38;5;43mFor example:
\t\\033[38;5;228m${cuseco} contentsubdirectory/holaholita.md \033[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source Continua.fu
 
##FILES
autohelp="${cuseco}.tmp"
alisfile="/Users/violetagonzalezgarcia/gitclones/.bash_aliases"
##DIRECTORIES 
bbdir=$(grep "cifo=" ${alisfile} | grep -o "/home[^']*" ) 
#VARIABLES
only=false

while getopts ":eho" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;;
		o)
		 	only=true
			;;	
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN
[[ -e ${mdfp} ]] && echo -e "it exists already!!" && ls ${mdfp} && exit

mdfp=$1 #md full path
cd ${bbdir}  
hugo new ${mdfp} >| ${autohelp}   
md=$(grep -o "/[^:][^ ]*" ${autohelp})
rm ${autohelp}  
sed -i '' "s/\"$/\" /" ${md}  
echo -e "→ ${md} "
continua
[[ ${only} = false ]] && vim +$ ${md}  
