#!/bin/bash
function whatis() {
	cuseco=$(basename $0)
    echo -e "\033[38;5;118m${cuseco} → \033[38;5;11mtype:\033[38;5;118mvio-bas-learn: python cd select vim python"
	echo -e "\033[38;5;118m⇒  \033[38;5;195mSelect py file en \033[38;5;11mdefault → oopdir \033[38;5;195m or if \033[38;5;9mc option \033[38;5;195mcurrent directory.
	Y \033[38;5;118mcommand → \$1 → \033[38;5;208mvim, cat, rm, 🐍 (python3.9) \033[38;5;195m or if \033[38;5;9mt option \033[38;5;208m mv, cp \033[38;5;195mto either \$2 or read newname. 
	⭐\033[38;5;11mdefault \$1 \033[38;5;118m C A T ⭐ ❤️️ 
\t\\033[38;5;43mFor example:
\t👉\t\033[38;5;228m${cuseco} -t mv \033[38;5;218m[new name here for the \033[38;5;228m\$REPLY file\033[38;5;218m, or get asked for it] \033[0m"
}

##FUNCTIONS
source Opte.fu
source Asksure.fu

function getname() {
	[[ ${trasiego} = true ]] && read -p " New name → " newname
	whereto=${destdir}/${newname}
}
##DIRECTORIES  
curdir=$(pwd)
pyfcdir=/Users/violetagonzalezgarcia/gitclones/.filecollections_vio/pyfiles
oopdir=/Users/violetagonzalezgarcia/gitclones/.filecollections_vio/pyfiles/oop-completebootcamp
##FILES
#VARIABLES
trasiego=false
collect=false
dcommand=("vim" "mv" "cp" "rm" "pyr")

while getopts  ":ehtc" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		t)
			trasiego=true
			;;
		c)
			collect=true
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1)) 

### MAIN
for c in $(echo "${dcommand[@]}")
do
	[[ ${c} == $1 ]] && dcommand=${c} && break  || dcommand="cat"
done
[[ ${dcommand} == "pyr" ]] && dcommand="/usr/bin/python3.9" 

if [[ ${collect} = false ]]; then 
	wherein=${oopdir} && destdir=${curdir}
else
	wherein=${curdir} && destdir=${oopdir} 
fi

select dpyf in $(find ${wherein} -type f -name "*py" -exec basename {} \; )
do
	[[ $2 ]] && newname=$2 || getname
	pyf=${wherein}/${dpyf}   
	[[ ${dcommand} != "vim" ]] && ${dcommand} ${pyf} ${whereto} || ${dcommand} ${pyf}
	break
done	
