#!/bin/bash

regex=$1
tmpfile=$0.tmp
function whatis() {
	cuseco=$(basename $0)
	echo -e "\033[38;5;118m${cuseco} ⇒  \033[38;5;11mtype:\033[38;5;118mvio-helper ⇒  ls for seq wc -l awk sed ⇒  work with files named with whitespaces"
	echo -e "\033[38;5;195m Savo todos files by regex \$1 en un tmp file \033[38;5;11m⭐ los quoto y trabajo con ellos foring el wcl y seding line numbes \033[38;5;11m⭐ \033[38;5;195m más lo que quiera añadir \033[38;5;212m BETIKO LO EDITO A MANIXA ❤️️ 
	\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
}

source Asksure.fu
source Opte.fu
source Continua.fu

while getopts ":eh" o; do
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis
#			echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))

#MAIN

echo -e "\033[38;5;118m"
read -p "have u opted first ???" anything
continua
ls *${regex}* | xargs -i echo "\"{}\"" >| ${tmpfile} 

for i in $(seq $(wc -l ${tmpfile} | awk '{print $1}'))
do
	dfile=$(sed -ne "${i}p" ${tmpfile})
	# 👉 EDIT HERE 
	# por ejemplo → 
	# read -p "new name → " newname
	# [[ ${newname} =~ "\.mp4" ]] && echo -n "" || newname=${newname}.mp4

done
rm ${tmpfile}  
