#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
	echo -e "\033[38;5;118m${cuseco} ⇒  \033[38;5;11mtype:\033[38;5;118mvio-helper ⇒  read newname cp plantillas-folder"
	echo -e "\033[38;5;195mCada \033[38;5;11m⭐ s.sh \033[38;5;11m⭐ \033[38;5;195m si me parece reutilizable: \033[38;5;212m la guardo como plantilla ❤️️ 
	\033[38;5;118m★ \033[38;5;9moption r \033[38;5;195mretocar \033[38;5;9m(\033[38;5;195mantes de guardar\033[38;5;9m) 🚁  
\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -r\033[0m"
	return 25
}


## SOURCES 
##VARS-FILES
source Asksure.fu
source Opte.fu
source Continua.fu
source Echocolors.fu # black red green yellow blue magenta cyan white pink orange whiteguay @+N
##FUNCTIONS

##DIRECTORIES 
curdir=$(pwd)
plantillasdir="/Users/violetagonzalezgarcia/gitclones/pruebas/plantillaSH"
##FILES
dfile="s.sh"
#VARIABLES
datevar=$(date +%m%d-%Hh%Mm)

while getopts ":ehr" o; do 
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		r)
			vim s.sh
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1))

### MAIN
echo -e "\033[38;5;14mNombre descriptivo de la plantilla (espacios \033[38;5;190m√ \033[38;5;14m; sin \033[38;5;228mext\033[38;5;14m) \033[38;5;195m" 
read -p "Nombre → " desc
set -x
desc=$(echo ${desc} | sed -ne "s/ /_/gp")
desc=${desc}-${datevar}.sh  
echo -e "\033[38;5;190m ${desc} \033[38;5;228m??"
continua
mv ${dfile} ${plantillasdir}/${desc}  
tree ${plantillasdir}  
