#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\033[38;5;118m${cuseco}	→ \\033[38;5;11mtype:\\033[38;5;118mvio-basadmin → grep, vim » bin-scripts; "

	echo -e "\033[38;5;118m ⇒  \\033[38;5;195mAplica \\033[38;5;11mdefault show vio.sh help \\033[38;5;195mo lista de args \\033[38;5;11m\$@ \\033[38;5;195msi la hay, sobre los \\033[38;5;11m⭐ \\033[38;5;195mmy bin scripts \\033[38;5;11m⭐\\033[38;5;195m \\033[38;5;212m❤️️ \\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o 
	\033[38;5;212mUN-aliasED \\033[38;5;195mgrep [^-]type \\033[38;5;11m» \\033[38;5;118mgret \033[38;5;195m→ RUN gres \033[38;5;11m"the script" 
	\033[38;5;212mUN-aliasED \\033[38;5;195mshao | grep \\033[38;5;11m» \\033[38;5;118mgres \033[38;5;195m→ RUN gres \033[38;5;11m"the script" 
	"
}

## SOURCES 'S
##VARS-FILES 'B
##FUNCTIONS 'F
source Opte.fu
source Asksure.fu
##DIRECTORIES 'D
curdir=$(pwd)
bindir="/Users/violetagonzalezgarcia/gitclones/bin"
##FILES 'I
tmpfileSHOW="/Users/violetagonzalezgarcia/gitclones/bin/gresSHOW.tmp"
tmpfile="/Users/violetagonzalezgarcia/gitclones/bin/gres.tmp"

#VARIABLES 'V

while getopts ":eh" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1))

### MAIN
if [[ ! $1 ]]; then
	whattodo="\"\$l\" -h"
else
	whattodo="$@"
fi
find ${bindir} -maxdepth 1 -type f -executable -exec basename {} \; >| ${tmpfileSHOW}  
find ${bindir} -maxdepth 1 -type f -executable >| ${tmpfile}
while read -r l
do 
	if [[ ! $1 ]]; then
		$l -h
	else
		fipa=$(grep "$l" ${tmpfile})
		whattodo="$@"
#		echo -e "\033[38;5;11m INIT HERE \033[0m "
		if [[ ${whattodo} =~ "grep" ]]; then
			todo=$(${whattodo} ${fipa} )
			[[ ${todo} ]] && echo -en "\033[38;5;195m ⭐⭐⭐ $l " && echo -e "\\033[38;5;118m" && ${todo}  
		else
			${whattodo} ${fipa}
		fi
	fi
done < ${tmpfileSHOW}  

rm ${tmpfileSHOW}  ${tmpfile}
