#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\033[38;5;118m${cuseco}	⇒ 	\033[38;5;11mtype:\033[38;5;118mvio-basadmin → nmap, /etc/hosts, casipi"
echo -e "	\033[38;5;195m Automate ssh to casipi \033[38;5;11m⭐ \033[38;5;195m git work!! \033[38;5;11m⭐\033[38;5;195m \033[38;5;212m❤️️ \n\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
}

## SOURCES 
##VARS-FILES 
##FUNCTIONS 
source Opte.fu
source Asksure.fu
function Dpiips() {
	echo -e "\033[38;5;159mwhat are the casipi ips by nmap and in /etc/hosts??" 
	nmpiip=$(sudo nmap -sL --traceroute 192.168.1.* | grep casipi | grep -o "\([0-9]\|\.\)*")
	ehpiip=$(grep casipi /etc/hosts | awk '{print $1}' | grep -v "\#")
}

##DIRECTORIES 
##FILES 
#VARIABLES 

while getopts ":eh" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN 

Dpiips

if [[ "${ehpiip}" != "${nmpiip}" ]]; then
  echo -e "\033[38;5;9mNope \\033[38;5;118m	⇒ 	"  
  sudo sed -ne "s/${ehpiip}/${nmpiip}/p" /etc/hosts 2>/dev/null
fi
[[ ${nmpiip} != "" ]] && echo -e "\033[38;5;11m→ nmpiip	⇒ 	${nmpiip}  " || echo -e "\033[38;5;11m→ nmpiip   ⇒  \033[38;5;9mCLOSED!! \033[0m"  
echo -e "\033[38;5;11m→ ehpiip	⇒ 	${ehpiip}  " 
[[ "${nmpiip}" != "${ehpiip}" ]] && echo -e "\033[38;5;123mnmap gets other than in /etc/host\033[38;5;127m!!! \033[0m" && exit || echo -e "\033[38;5;194migualis!!!"  
