#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\033[38;5;118m${cuseco}	⇒ 	\\033[38;5;11mtype:\\033[38;5;118mvio-basadmin ⇒  clog → vim bash-clog by date as $1"
echo -e " \033[38;5;11mDE MOMENTO :  \\\033[38;5;195m Ver el clog del día \$1 \\033[38;5;11m⭐\\033[38;5;195m solo 2022 \\033[38;5;11m⭐\\033[38;5;195m \\033[38;5;212m❤️️ \\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} 15\033[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS 
source Opte.fu
source Asksure.fu
function showdays() {
	echo -e "\033[38;5;11m"	
	ls ${clogdir} | grep -o "2022[^\.]*"
}
function selectplus() {
   echo -e "\033[38;5;118mSelect day and continue??"
   if asksure; then
	   echo -e "\033[38;5;118m"  
	   tosel=()
	   let count=0
	   for da in $(showdays)
	   do
		  [[ ${count} > 0 ]] && tosel+="${da} "
		  let count=${count}+1 
	   done
	   select ddate in $(echo ${tosel[@]})
	   do
		   ddate=${ddate}
		  break
	   done 
   else
	   echo -e "\033[38;5;212m❤️️  ❤️️  ❤️️  ❤️️  Ciao \\033[38;5;118m!!!!!!!⭐🤗 🤗!!"  
	   exit
   fi
}	   
function dmain() {
	clogfile=$(ls ${clogdir}/*2022* | grep ${ddate} )
	if [[ -f ${clogfile} ]]; then
	   vim ${clogfile}  
	else
		echo -e "\033[38;5;9m no existe clog del \\033[38;5;195m ${ddate} \\033[38;5;212m!!!"
	fi	
}
##DIRECTORIES
clogdir=/Users/violetagonzalezgarcia/gitclones/.clogs
curdir=$(pwd)
##FILES 
#VARIABLES
if [[ ! $1 ]]; then
	echo -e "\033[38;5;14mEl día coño!!!!"
	exit
elif [[ $1 == "y" ]]; then
	ddate=$(date -d '-1 day' +%Y-%m-%d)
elif [[ $1 == "h" ]]; then
	ddate=$(date +%Y-%m-%d)
else
	dday=$1
	if [[ $2 ]]; then
		dmonth=$2
	else
		dmonth=$(date +%m)
	fi
	ddate="${dmonth}-${dday}"  
fi


while getopts ":ehs" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		s)
			showdays
			selectplus
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN
dmain
