#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\033[38;5;118m${cuseco} → \033[38;5;11mvio-helpers:\033[38;5;118mwhile ls -tr nl sleep clear"
	echo -e "\033[38;5;118m⇒  \033[38;5;195mlaunch it to ls dir con los files numerados de más viejo a más reciente
	⭐\033[38;5;195m pensado para observar un dir en el que voy saving files downloaded ⭐ ❤️️ 
\t\\033[38;5;43mFor example:
\t\\033[38;5;228m${cuseco} -$o\033[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu

#function eyeing() { }

#function eyebreak() { }

##DIRECTORIES 
##FILES
#VARIABLES
breakit=false
dir=$(pwd)

while getopts ":ehbd" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		b)
			breakit=true
			;;
		d)
			dir=${@: -1}
			;;
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

togrepfb=$@
### MAIN
[[ ${togrepfb} == "" ]] && togrepfb="fallbackgrepsomethingifhterearenoargs"  

while true
do
	clear
	echo "⇒  $(pwd | sed -ne 's?/.*\(/[^/]*/[^/]*$\)?\1?p')" 
	ls -tr ${dir} | grep -v "${togrepfb}" | nl
	sleep 5s 
	if [[ ${breakit} == true ]]; then 
		if asksure; then
			continue
		else
			break
		fi
	fi
done
