#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
	echo -e "\033[38;5;118m${cuseco} ⇒  \033[38;5;11mtype:\033[38;5;118mvio-basadmin ⇒  cd, sed alis file"
	echo -e "\033[38;5;195m a dónde \033[38;5;11m⭐ hay que ir \033[38;5;11m⭐ \033[38;5;195m rápido \033[38;5;212m rapidito ❤️️ 
	\033[38;5;118m★ \033[38;5;9moption c \033[38;5;195malternativa cde 🚁  
	\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
	return 25
}
	

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu
##DIRECTORIES
##FILES
alisfile=/Users/violetagonzalezgarcia/gitclones/.bash_aliases
#VARIABLES
cdaocde=cda
newcda=$1
### MAIN
while getopts ":ehc" o; do 
	case "${o}" in
		e)
			opte
			exit
			;;
		h)
			whatis
#			echo -e "PENDING whatis!! 🔥 "
			exit
			;;
		c)
			cdaocde=cde
			;;
		\?)
			echo "invalid option: -$OPTARG"
			exit
			;;
	esac
done
shift $((OPTIND-1))

[[ ! -e $1 ]] && newcda=$(pwd)

echo -e "\033[38;5;228mAND NEW \033[38;5;11m${cdaocde} ⭐⭐⭐\\033[38;5;195m $(sed -ne "/^alias ${cdaocde}=/s?=.*?=\'${newcda}\'?p" ${alisfile})\\033[38;5;118m?????????????"
if asksure; then
	sed -i '' "/^alias ${cdaocde}=/s?=.*?=\'cd ${newcda}\'?" ${alisfile}   
	echo -e "\033[38;5;11mD✨NG!!!!"
    echo -e "\033[38;5;14m$(sed -ne "/^alias ${cdaocde}=/p" ${alisfile}) \033[0m"  	
else
	echo -e "\033[38;5;118mCome back with the \\033[38;5;212mrealpath \\033[38;5;118mdir!! "
fi
