#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\033[38;5;195m\\033[38;5;118m${cuseco}	⇒ 	\\033[38;5;11mtype:\\033[38;5;118mbin work ⇒  mv → /bin/funciones"
echo -e " \033[38;5;195m sends cprue/sh files to BIN without .sh \\033[38;5;212m ❤️️ \\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m\\n
    "
}

#VARIABLES

##DIRECTORIES
ddir=/Users/violetagonzalezgarcia/gitclones/bin/funciones/fproespecific
##FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu
#gralgetops

### MAIN
while getopts ":eh" o; do 
	gralGetops
done
shift $((OPTIND-1))
# ♥

dshfile=$1
dfile=$(realpath ${dshfile}) 

echo -e "\033[38;5;195m Type \\033[38;5;118m[Aa] \\033[38;5;195m for a \\033[38;5;118mgeneral \\033[38;5;195m function. \\033[38;5;9m[Ee] \\033[38;5;195m for \\033[38;5;9mproespecific"        
if asksure; then
	ddir=${ddir%fproespecific}  
fi

mv ${dfile} ${ddir}   
tree /Users/violetagonzalezgarcia/gitclones/bin/funciones
