#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\033[38;5;118m${cuseco} → \033[38;5;11mtype:\033[38;5;118mvio-bas-admin: shao 1> grep rm"
	echo -e "\033[38;5;118m⇒  \033[38;5;195mRun shao, capture output, and grep it for \$1 
	⭐\033[38;5;195m ALGOESTRELLADO ⭐ ❤️️ 
\t\\033[38;5;43mFor example:
\t\\033[38;5;228m${cuseco} -$o\033[0m"
}

## SOURCES 
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
##DIRECTORIES 
##FILES
#VARIABLES

while getopts ":eh" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; 
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN

[[ ! $1 ]] && echo -e "\033[38;5;195mGreping \033[38;5;118mtype\033[38;5;195m!!!" && term2grep=$1 || term2grep=$1 

shao 1> shaotmp 2>/dev/null ; grep -B1 ${term2grep} shaotmp; rm shaotmp
