#!/bin/bash
function whatis() {
	cuseco=$(basename $0)
	echo -e "\033[38;5;118m${cuseco} ⇒  \033[38;5;11mtype:\033[38;5;118mvio-helper ⇒  sed .bash_aliases vim emptypru/sh"
	echo -e "\033[38;5;195m para \033[38;5;11m⭐ fast vim \033[38;5;11m⭐ \033[38;5;195m del sh of the day \033[38;5;212m siempre desde emptypru ❤️️ 
	\033[38;5;118m★ \033[38;5;9moption option \033[38;5;195mquehace 🚁  
	\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
	return 25
}


## SOURCES 
##VARS-FILES
source Asksure.fu
source Opte.fu
source Continua.fu
source Echocolors.fu # black red green yellow blue magenta cyan white pink orange whiteguay @+N
##FUNCTIONS
##DIRECTORIES 
emptypru="/Users/violetagonzalezgarcia/gitclones/pruebas/emptypru"
##FILES
alisfile="/Users/violetagonzalezgarcia/gitclones/.bash_aliases"
nowsh="${emptypru}/$(grep "nowsh=" ${alisfile} | sed -ne 's/.*=//p')"
#VARIABLES

while getopts ":eh" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis 2>/dev/null
			[[ "$?" == 25  ]] || echo -e "PENDING whatis!! 🔥 "
			;; 
		?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
done
shift $((OPTIND-1))
### MAIN
if [[ $1 ]]
then
	nowsh=$1 
	echo -e "\033[38;5;190m👉 nowsh\033[38;5;228m=\033[38;5;190m${nowsh} \033[38;5;11m??? \033[0m"     
	continua
	sed -i '' "s/nowsh=.*/nowsh=${nowsh}/" ${alisfile}
 	echo -e "Type \033[38;5;218msal 💕 " 	
else
	vim ${nowsh} 
fi	
