#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
    echo -e "\\033[38;5;118m${cuseco}	→ \\033[38;5;11mtype:\\033[38;5;118mvio-basadmin: clog, ..., vim"
	echo -e "\\033[38;5;118m ⇒  \\\033[38;5;195mget curretn oclog and vim it  \\033[38;5;11m⭐\\033[38;5;195mALGOESTRELLADO \\033[38;5;11m⭐\\033[38;5;195m \\033[38;5;212m❤️️ \\n\\033[38;5;43m\t👉\t\033[38;5;11m${cuseco} -$o\033[0m"
}

## SOURCES 'S
##VARS-FILES 'B
##FUNCTIONS 'F
source Opte.fu
source Asksure.fu
##DIRECTORIES 'D
clogdir=/Users/violetagonzalezgarcia/gitclones/.clogs/maestros
##FILES 'I
#VARIABLES 'V

while getopts ":eh" o; do
	case ${o} in
		e)
			opte
			exit
			;;
		h)
			whatis
			exit
			;; # 'O
?)
			echo -e "Nein nein nein option → ${o}"
			exit
			;;
	esac
    
done
shift $((OPTIND-1))

### MAIN 'M
senal=$(sed -ne '25,32p' /Users/violetagonzalezgarcia/gitclones/.bashrc | grep true)
if [[ ${senal} != "" ]]; then
	dclog=$(echo ${senal} | sed -ne "s/=true/.oclog/p")
else
	echo -e "no signal!!!!!!!!!"
	exit
fi

vim ${clogdir}/${dclog}  
