#!/bin/bash

function whatis() {
	cuseco=$(basename $0)
 echo -e "\e[38;5;118m${cuseco}	⇒ 	\\e[38;5;11mtype:\\e[38;5;118mln ⇒  linkar el log named by dir a la .filecollections_vio/logs"
echo -e "	\\e[38;5;195m Log current dir AND link it to file collections\\e[38;5;11m⭐\\e[38;5;195m ol'open_a_log_file\\e[38;5;11m⭐\\e[38;5;195m \\e[38;5;212m❤️️ \\n\\e[38;5;43m\t👉\t\e[38;5;11m${cuseco} -$o\e[0m"
}

## SOURCES
##VARS-FILES
##FUNCTIONS
source Opte.fu
source Asksure.fu
source GralGetops.fu 
##DIRECTORIES
##FILES
#VARIABLES

### MAIN
while getopts ":eh" o; do
    gralGetops
done
shift $((OPTIND-1))



#!/bin/bash

#asignar las variables de la funcion, del header, del dest dir
cold="/home/violeta/.filecollections_vio/logs"

#tomar dir name de origen
dir=`pwd | xargs -i basename {}` 
ext=log
file=.${dir}.${ext}

/home/violeta/.registro_actividad_diario.viovim +$ $file
ln -f -t ${cold} ${file}   
exit
